### ISSUE TITLE
Rust 1.32.0 is released

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1141]
Today, rust 1.32.0 is announced.
This version removes jemalloc by default.
@foriequal0 Would you check whether this version works with HeapSizeOf?
Even though https://github.com/CodeChain-io/codechain/pull/1130 removes most of HeapSizeOf, memory db still uses it.

**Comment by foriequal0** [comment]
HeapSizeOf is not working on Mac with 1.32.0. 
```bash
error: linking with `cc` failed: exit code: 1
  |
...
  = note: Undefined symbols for architecture x86_64:
            "_je_malloc_usable_size", referenced from:
                heapsize::heap_size_of_impl::h4983f5bd6a2b8fb6 in libheapsize-7c05fdd28eb8437a.rlib(heapsize-7c05fdd28eb8437a.heapsize.tq28rc9u-cgu.3.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It works on linux yet.
However the reported size is slightly different between allocators.

**Comment by foriequal0** [comment]
Changing `link_name` in `heapsize` crate to `malloc_size` from `malloc_usable_size` seems working but it reports different than jemalloc.

**Comment by sgkim126** [comment]
@foriequal0 Thank you.
Let's postpone the upgrade until we find an appropriate solution.

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/commit/dafbe042594c7e8926c857e65c91c35204068863
