### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#262]
Integration tests fail with the following message.

```
 FAIL  src/basic.test.ts
  ✕ basic scenario (940ms)

  ● basic scenario

    TypeError: this.process.off is not a function

      72 |         if (line.includes("Initialization complete")) {
      73 |           readline.close();
    > 74 |           this.process!.off("error", onError);
         |                         ^
      75 |           resolve();
      76 |         }
      77 |       });

      at Interface.readline.on.line (src/helper/spawn.ts:74:25)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.749s
Ran all test suites.
```

I use macOS High Sierra and my node version is v8.10.0.

**Comment by kseo** [comment]
Run integration tests on Travis once this issue is fixed. See #237

**Comment by kseo** [comment]
@Kais-DkM After rebasing to the latest revision, the test fails with timeout:

```
 FAIL  src/basic.test.ts (8.239s)
  ✕ basic scenario (5030ms)

  ● basic scenario

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      35 | }
      36 |
    > 37 | test("basic scenario", async () => {
         | ^
      38 |   await instance.start("cargo", ["run", "--", "-c", "solo"]);
      39 |   const nonce = await instance.sdk.getNonce(address);
      40 |   const hash = await instance.sdk.sendSignedParcel(payment(nonce!).sign(secret));

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Object.<anonymous> (src/basic.test.ts:37:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.351s
Ran all test suites.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c cd ..; cargo build; cd test; jest
Directory: /Users/kseo/codechain/test
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kseo/codechain/test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Kais-DkM** [comment]
I got simillar message when main program was not built yet.
@kseo Could you run `cargo build` first and check if same error occurs again?

**Comment by Kais-DkM** [comment]
I can't reproduce issue in my local machine, but there are some reports that shows similar errors.
Please let me know if anyone finds exact situation to reproduce this problem.

**Comment by kseo** [comment]
@Kais-DkM It is broken again.

```
 FAIL  src/basic.test.ts
  ● Test suite failed to run

    TypeError: codechain_sdk_1.H256 is not a constructor

      19 | import CodeChain from "./helper/spawn";
      20 |
    > 21 | const secret = new H256("ede1d4ccb4ec9a8bbbae9a13db3f4a7b56ea04189be86ac3a6a439d9a0a1addd");
         |                ^
      22 | const address = new H160(privateKeyToAddress(secret.value));
      23 |
      24 | const instance = new CodeChain();

      at Object.<anonymous> (src/basic.test.ts:21:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.079s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codechain-integration-test@0.1.0 start: `cd ..; cargo build; cd test; jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codechain-integration-test@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kseo/.npm/_logs/2018-07-09T23_07_58_951Z-debug.log
```

**Comment by joojis** [comment]
https://github.com/CodeChain-io/codechain/pull/636/commits/e057712ea6d0e287b45bc6f94fc469aeae216774
